In [1]:
import torch

In [2]:
# 需要求导的，可以手动定义
# 方法1
x = torch.randn(3, 4, requires_grad=True)
x

tensor([[-0.7448, -0.7946, -0.6422, -0.5685],
        [ 0.5684,  1.4038, -0.2684, -0.3274],
        [ 1.3735,  0.0489,  0.8083, -0.0633]], requires_grad=True)

In [3]:
# 方法2
x = torch.randn(3, 4)
x.requires_grad=True
x

tensor([[-0.7110,  0.6571, -1.2384,  0.3292],
        [-0.7625,  0.3003,  0.6437,  0.4181],
        [ 0.2191,  0.0376,  0.8074, -0.0580]], requires_grad=True)

In [4]:
b = torch.randn(3, 4, requires_grad=True)

In [7]:
b

tensor([[-0.0706, -1.4473,  0.8292, -0.8002],
        [-0.0414,  1.7950,  0.3438,  0.1863],
        [ 1.0737,  0.3253, -1.5111, -0.0710]], requires_grad=True)

In [5]:
t = x + b

In [6]:
t

tensor([[-0.7816, -0.7902, -0.4092, -0.4710],
        [-0.8039,  2.0954,  0.9876,  0.6045],
        [ 1.2928,  0.3628, -0.7037, -0.1290]], grad_fn=<AddBackward0>)

In [8]:
y = t.sum()

In [9]:
y

tensor(1.2543, grad_fn=<SumBackward0>)

In [10]:
# 反向传播
y.backward()
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
x.requires_grad, b.requires_grad, t.requires_grad

(True, True, True)

In [12]:
# 计算流程
x = torch.rand(1)
b = torch.rand(1, requires_grad=True)
w = torch.rand(1, requires_grad=True)
y = w * x
z = y + b

In [13]:
x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad

(False, True, True, True)

<b>反向传播计算</b>

In [14]:
z.backward(retain_graph=True)   # 如果不清空会累加起来

In [15]:
w.grad

tensor([0.2936])

In [16]:
b.grad

tensor([1.])

In [17]:
x

tensor([0.2936])