In [1]:
import torch
import numpy as np

<ul>
    <li>0.scalar</li>
    <li>1.vector</li>
    <li>2.matrix</li>
    <li>3.n-dimensional tensor</li>
</ul>

<b>Scalar</b>

通常是一个数值

In [2]:
x = torch.tensor(42.)
x

tensor(42.)

In [3]:
x.dim

<function Tensor.dim>

In [4]:
2 * x

tensor(84.)

In [5]:
x.item()

42.0

<b>Vector</b>

In [6]:
v = torch.tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [7]:
v.dim()

1

In [8]:
v.size()

torch.Size([3])

<b>Matrix</b>

In [9]:
M = torch.tensor([[1., 2.], [3., 4.]])

In [10]:
M

tensor([[1., 2.],
        [3., 4.]])

In [11]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])